# =============================================================================
# backend/models/pipeline_run.py
#
# PipelineRun model tracking autonomous analytical execution runs.
# =============================================================================

from typing import TYPE_CHECKING, Optional, Dict, Any, List
import uuid

from sqlalchemy import ForeignKey, String, Text, JSON
from sqlalchemy import Uuid as UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from models.base import Base

if TYPE_CHECKING:
    from models.project import Project
    from models.dataset import Dataset
    from models.model_artifact import ModelArtifact
    from models.report import Report


class PipelineRun(Base):
    """
    PipelineRun model representing an execution run of the Autonomous Data Scientist agent.
    Captures the planner's progress, goal, plan, logs, and any runtime errors.
    """
    __tablename__ = "pipeline_runs"  # Custom tablename if different from default plural rules

    goal: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        doc="Natural language goal input by the user.",
    )

    status: Mapped[str] = mapped_column(
        String(50),
        default="pending",
        nullable=False,
        doc="Current status of the run (e.g. pending, planning, running, plan_approval_pending, completed, failed).",
    )

    plan: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JSON,
        nullable=True,
        doc="JSON structure of steps generated by the Planner Agent.",
    )

    execution_logs: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JSON,
        nullable=True,
        doc="Structured logs detailing agent execution steps and outcomes.",
    )

    error_message: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        doc="Error traceback or descriptive message in case of failure.",
    )

    runtime_metrics: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JSON,
        nullable=True,
        doc="Runtime characteristics (e.g., duration in seconds, token cost, LLM calls).",
    )

    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        doc="Foreign key reference to the project containing this run.",
    )

    dataset_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(),
        ForeignKey("datasets.id", ondelete="SET NULL"),
        nullable=True,
        doc="Foreign key reference to the primary dataset used for this run.",
    )

    # Relationships
    project: Mapped["Project"] = relationship(
        "Project",
        back_populates="pipeline_runs",
        doc="The project workspace containing this run.",
    )

    dataset: Mapped[Optional["Dataset"]] = relationship(
        "Dataset",
        back_populates="pipeline_runs",
        doc="The dataset analyzed in this run.",
    )

    models: Mapped[List["ModelArtifact"]] = relationship(
        "ModelArtifact",
        back_populates="pipeline_run",
        cascade="all, delete-orphan",
        doc="Model artifacts generated by this run.",
    )

    reports: Mapped[List["Report"]] = relationship(
        "Report",
        back_populates="pipeline_run",
        cascade="all, delete-orphan",
        doc="Analytical reports generated by this run.",
    )
