# =============================================================================
# backend/api/v1/endpoints/chat.py
#
# WebSocket endpoints for streaming chat with the LangGraph agent.
# =============================================================================

import logging
from fastapi import APIRouter, WebSocket, WebSocketDisconnect
from langchain_core.messages import HumanMessage
from graphs.chat_graph import chat_app

router = APIRouter()
log = logging.getLogger(__name__)

@router.websocket("/stream/{session_id}")
async def websocket_endpoint(websocket: WebSocket, session_id: str):
    """
    Bidirectional WebSocket for streaming chat interactions.
    """
    await websocket.accept()
    log.info(f"WebSocket connected for session: {session_id}")
    
    # We use the session_id as the thread_id for LangGraph checkpointer memory
    config = {"configurable": {"thread_id": session_id}}
    
    try:
        while True:
            # Receive user message
            user_text = await websocket.receive_text()
            
            if user_text.lower() == "exit":
                break
                
            input_message = HumanMessage(content=user_text)
            
            # Stream events from LangGraph
            # astream_events yields tokens as they are generated by the LLM
            async for event in chat_app.astream_events({"messages": [input_message]}, config, version="v1"):
                kind = event["event"]
                
                # Stream LLM tokens directly to the client
                if kind == "on_chat_model_stream":
                    content = event["data"]["chunk"].content
                    if content:
                        await websocket.send_text(content)
                        
                # Optionally notify client when a tool is called
                elif kind == "on_tool_start":
                    tool_name = event["name"]
                    await websocket.send_text(f"\n*[System: Running {tool_name}...]*\n")
                    
            # Send a distinct delimiter to tell the frontend the stream is done
            await websocket.send_text("[DONE]")
            
    except WebSocketDisconnect:
        log.info(f"WebSocket disconnected for session: {session_id}")
    except Exception as e:
        log.error(f"WebSocket error: {e}")
        await websocket.send_text(f"\nError: {str(e)}")
        await websocket.close(code=1011)

@router.get("/history/{session_id}")
async def get_chat_history(session_id: str):
    """
    Retrieves the chat history from the LangGraph memory checkpointer.
    """
    config = {"configurable": {"thread_id": session_id}}
    # Fetch the state from the checkpointer
    state_snapshot = chat_app.get_state(config)
    
    if not state_snapshot or not state_snapshot.values:
        return {"messages": []}
        
    # Serialize messages for the frontend
    messages = []
    for msg in state_snapshot.values.get("messages", []):
        msg_type = "user" if isinstance(msg, HumanMessage) else "ai" if msg.type == "ai" else "system"
        if msg_type in ["user", "ai"]: # Only send user and AI messages to UI
            messages.append({"role": msg_type, "content": msg.content})
            
    return {"messages": messages}
